### ISSUE TITLE
[Feature request] Expose methods to apply tics on a single axis

### ISSUE THREAD

**Issue by BlobCodes** [crystal-data/aquaplot#20]
There already is the Plot.set_tics method, but we can't apply tics on a single axis (x, y, z, x2, y2, cb). This would be very helpful!

**Comment by christopherzimmerman** [comment]
This one is a bit tricky, since I don't really keep track of which ticks on which axes have been set, just allow a string.  For now, I'll add an axes_hash that is used if the regular ticks attribute is empty (which it is by default).  Fair warning, I don't really work on this library anymore, so no guarantees it will continue to work!

I will most likely respond to bug fixes / minor issues however.

**Comment by christopherzimmerman** [comment]
Alright, change has been made, here is an MCVE of the new behavior:

```
fns = ["sin(x)", "cos(x)", "tan(x)", "atan(x)", "asin(x)"].map do |fn|
  AquaPlot::Function.new fn
end

plt = AquaPlot::Plot.new fns
plt.set_axis_ticks("x", "scale 10")
plt.set_axis_ticks("y", "scale 1")
plt.show
plt.close
```

![test](https://user-images.githubusercontent.com/7414804/71687845-4a045980-2d64-11ea-81b4-25989a9006da.png)
